version: '3.3'
services:
  php-apache-environment:
    image: nickenoctaviana/quiz2
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./erp/:/var/www/html/
    ports:
      - 8000:80
    networks:
      - kuis2sister

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: erp3
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./erp/database/erp3.sql:/docker-entrypoint-initdb.d/erp3.sql
    networks:
      - kuis2sister

volumes:
  db:

networks:
  kuis2sister:
    # name: kuis2sister-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24